name: Build and Package IzPack Installer

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Compile IzPack Installer
        run: |
          java -jar libs/izpack-dist-5.2.3.jar -b installer/src/main/resources -f installer/src/main/resources/install.xml -o output/installer.jar

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: output/installer.jar
